name: example
publish_to: "none"

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
