name: provider
description: A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 6.1.2

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  collection: ^1.15.0

  flutter:
    sdk: flutter

  nested: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
